package graphics.kiln.rosella.render.graph.resources;

import org.lwjgl.vulkan.*;

public class VulkanBitmasks {

    public static final int ALL_WRITE_ACCESS_BITS = VK10.VK_ACCESS_SHADER_WRITE_BIT | VK10.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK10.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT | VK10.VK_ACCESS_TRANSFER_WRITE_BIT | VK10.VK_ACCESS_HOST_WRITE_BIT | VK10.VK_ACCESS_MEMORY_WRITE_BIT | EXTTransformFeedback.VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT | EXTTransformFeedback.VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT | KHRAccelerationStructure.VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR | NVDeviceGeneratedCommands.VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV;
    public static final int ALL_READ_ACCESS_BITS = VK10.VK_ACCESS_INDIRECT_COMMAND_READ_BIT | VK10.VK_ACCESS_INDEX_READ_BIT | VK10.VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT | VK10.VK_ACCESS_UNIFORM_READ_BIT | VK10.VK_ACCESS_INPUT_ATTACHMENT_READ_BIT | VK10.VK_ACCESS_SHADER_READ_BIT | VK10.VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK10.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK10.VK_ACCESS_TRANSFER_READ_BIT | VK10.VK_ACCESS_HOST_READ_BIT | VK10.VK_ACCESS_MEMORY_READ_BIT | EXTTransformFeedback.VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT | EXTConditionalRendering.VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT | EXTBlendOperationAdvanced.VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT | KHRAccelerationStructure.VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR | EXTFragmentDensityMap.VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT | KHRFragmentShadingRate.VK_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR | NVDeviceGeneratedCommands.VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV;

    public static boolean hasWriteAccess(int accessMask) {
        return (accessMask & ALL_WRITE_ACCESS_BITS) != 0;
    }

    public static int getWriteAccesses(int accessMask) {
        return accessMask & ALL_WRITE_ACCESS_BITS;
    }

    public static boolean hasReadAccess(int accessMask) {
        return (accessMask & ALL_READ_ACCESS_BITS) != 0;
    }

    public static int getReadAccesses(int accessMask) {
        return accessMask & ALL_READ_ACCESS_BITS;
    }
}
